apiVersion: apps/v1
kind: Deployment
metadata:
  name: appnotas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appnotas
  template:
    metadata:
      labels:
        app: appnotas
    spec:
     tolerations:
     - key: "CriticalAddonsOnly"
       operator: "Exists"
       effect: "NoSchedule"
     containers:
     - name: appnotas
       image: dcruz06/appnotas2:v4
       imagePullPolicy: Always
       ports:
       - containerPort: 8080
